### ISSUE TITLE
Improve the high-load of the settlement engine

### ISSUE THREAD

**Issue by dora-gt** [emschwartz/interledger-rs#203] opened 2019-08-10 01:03 UTC
Though I haven't dug into so much about the problem, it seems that the load of the settlement engine is so high. It may be because of outputting a bunch of logs. Need an inspection and to make the reason clear.

**Comment by emschwartz** [comment] 2019-08-14 17:47
I am also seeing this issue:

![image](https://user-images.githubusercontent.com/3262610/63043287-ec956c00-be99-11e9-98d7-6f139bbd411e.png)

**Comment by gakonst** [comment] 2019-08-14 17:59
Probably has to do with https://github.com/emschwartz/interledger-rs/blob/master/crates/interledger-settlement-engines/src/engines/ethereum_ledger/eth_engine.rs#L240-L254. Will investigate.

**Comment by emschwartz** [comment] 2019-08-14 18:09
The problem is that it is trying to scan every single block since the beginning of the blockchain and firing off one HTTP request for each in parallel. 

```console
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Current block 12829885
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Will fetch txs from block 0 until 12829885
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Scanning history for incoming ETH transactions
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 0
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 1
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 2
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 3
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 4
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 5
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 6
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 7
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 8
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 9
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 10
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 11
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 12
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 13
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 14
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 15
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 16
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 17
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 18
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 19
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 20
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 21
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 22
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 23
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 24
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 25
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 26
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 27
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 28
[2019-08-14T18:06:43Z TRACE interledger_settlement_engines::engines::ethereum_ledger::eth_engine] Getting txs for block 29
```

**Comment by emschwartz** [comment] 2019-08-14 19:28
Oops... Sorry Infura!

![image](https://user-images.githubusercontent.com/3262610/63050072-2e2d1380-bea8-11e9-9320-8a4b779a66bc.png)

**Comment by gakonst** [comment] 2019-08-15 16:08
Can we close this?

**Comment by emschwartz** [comment] 2019-08-15 17:18
Fixed in https://github.com/emschwartz/interledger-rs/pull/213

**Closed by emschwartz** 2019-08-15 17:18 UTC
Labels: bug
